entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: proxy
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO # DEBUG|INFO|WARNING|ERROR|CRITICAL

accessLog:
  filePath: "/logs/traefik.log"
  format: json
  bufferingSize: 50
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep